### ISSUE TITLE
[Minecraft server Suggestion] - Sleep Percentages

### ISSUE THREAD

**Issue by DemonSlayer112** [partridge420x/Midnight-Gaming#14]
**Is your feature request related to a problem? If so Please describe.**
A clear and concise description of what the suggestion would be, How it would possibly be implemented. How it would be balanced into our current server. 
So far only a few people sleep, this makes it pretty hard to start your base with it being night a lot.
Also, even more difficult when you get through a night, build for 2 minutes then have a thunderstorm come.
Would be great if it only needed one person to sleep.

**Describe alternatives you've considered**
Some people may want night, tho this can be used mainly by mob farms, but if they want membranes or horsemen, then maybe people can do a `/dontsleep` to sort of prevent sleep. This would of course be guarded by rules to not abuse it and to have it only for phantoms, horsemen, ect

**Additional context**

**Comment by partridge420x** [comment]
Feature has been implemented
