### ISSUE TITLE
[Minecraft server Suggestion] - Combinable Village Trades

### ISSUE THREAD

**Issue by DemonSlayer112** [partridge420x/Midnight-Gaming#15]
**Is your feature request related to a problem? If so Please describe.**
A clear and concise description of what the suggestion would be, How it would possibly be implemented. How it would be balanced into our current server. 
Entities on servers are a issue sometimes. Many entities means many lag.
And villager trading halls seem to be unnecessarily large at times.
So, for example, take 3 villagers selling mending, infinity and protection 4.
And combine them! :D 
this way one villager can have all the important trades without using like over 9+ per play who has a trading hall.

**Describe alternatives you've considered**

**Additional context**

**Comment by partridge420x** [comment]
I've looked into optimizing villagers, and sadly all plugins regarding it are outdated, Though i have my eyes on a farming control plugin that would help with tps lag regarding mob farms
